<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration Date___privateStripeFrame8818</name>
   <tag></tag>
   <elementGuidId>2423a9c2-8458-4c2f-87cf-de878744141b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame8818']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame8818&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>464566fa-52bf-44ba-85ae-d169fe2e98e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame8818</value>
      <webElementGuid>55397431-d006-42e1-8680-bb113d98b635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f87806e-71ed-4e73-9520-5093c4fa83a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9b8f3ba-edad-414f-9965-fdf04fcbb0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bb4860e3-fe01-4943-badf-acc1277cb9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4b5d9541-db15-456b-a78f-9e93d557de5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>c9f95e1b-480e-48dc-a305-c8952dd12188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController8811</value>
      <webElementGuid>0aca14a6-a946-44f9-ac63-e356a52bbdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure CVC input frame</value>
      <webElementGuid>7bc11461-4487-43db-a947-842eab58de19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_cvc-653b618d7b205&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>a5dc3232-4cca-4030-b6e2-6a1f75097065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame8818']</value>
      <webElementGuid>299f66f2-e4a0-492e-9e7a-bb3fcd85e619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-page-card_cvc-653b618d7b205']/div/iframe</value>
      <webElementGuid>90eb43f3-8f70-436c-b7b6-0d5eaab8a4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/iframe</value>
      <webElementGuid>33ad07f7-aff7-4a32-b793-f81e7e1b097c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame8818' and @src = 'https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController8811' and @title = 'Secure CVC input frame']</value>
      <webElementGuid>876b8c19-f1f7-4c48-88ce-edc3a9ca3010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
