<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Last Name___privateStripeFrame3526</name>
   <tag></tag>
   <elementGuidId>d8b3d1da-fad1-4e17-8888-508deb5b36b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame3526']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame3526&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f44e515d-46ae-44c8-a896-6e1fedd4af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame3526</value>
      <webElementGuid>f56c2e71-52df-422e-8803-71d05b4ee4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8923c4c1-c78c-40fa-80bf-79ea3b94c3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9061f19f-cd1e-4547-9b1e-7f933f321b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>728b7974-f3bb-4d1c-aed3-b7a530b5a287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>915896e9-8c61-4e78-822a-d3cc623cf51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>28b80e0b-9d74-45ec-a7b8-27f8372b0565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController3521</value>
      <webElementGuid>dcc1cfd5-7d05-4772-a044-71dcec66837c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card number input frame</value>
      <webElementGuid>594b2777-e466-43fa-9430-65bc8385053c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_number-653b618d7b205&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>a77d83e6-25ef-434c-a4bc-4f1d55717549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame3526']</value>
      <webElementGuid>29f4d4f5-96bf-4393-b504-b221b24d6072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-page-card_number-653b618d7b205']/div/iframe</value>
      <webElementGuid>be4e67b4-6686-468c-8e80-eb3147599df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a0716ee5-01a9-4b38-8eef-ffce5c78cf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame3526' and @src = 'https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController3521' and @title = 'Secure card number input frame']</value>
      <webElementGuid>f6e99bad-4087-440c-8f3f-b2618d78dac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
