<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Number___privateStripeFrame5777</name>
   <tag></tag>
   <elementGuidId>637af5b0-c3b1-4f7f-bd03-e79d65e2f19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame5777']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame5777&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fb213c1d-2e3a-4cdc-89b0-aff62f383c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame5777</value>
      <webElementGuid>07a472da-02b4-408e-aec2-67717a038f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee2e60c5-db07-47a8-9346-5a5108014336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>772b4f8c-0a94-4e4b-bf8e-7183dbdcf187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2469ee50-b12c-4e96-9d45-acee739b9407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7a7107fc-cf2a-468f-ab2b-c56c0d5d4562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>72681d30-2dd7-4303-8283-f0f485cf07bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardExpiry&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController5771</value>
      <webElementGuid>04b00080-5c4a-4092-bce4-86ee22955038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure expiration date input frame</value>
      <webElementGuid>6ef4e4d3-d43d-44a9-b077-e580729a358a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_expiration_date-653b618d7b205&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>7ad68fb1-e708-44d7-abd3-99c0df8d49f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame5777']</value>
      <webElementGuid>4b50612a-b82d-4055-81e0-cfe7b6c78b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-page-card_expiration_date-653b618d7b205']/div/iframe</value>
      <webElementGuid>be4b0444-b6e9-4580-8103-e25ddea29d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/iframe</value>
      <webElementGuid>f1a3780c-b50b-4cec-b79d-1a0028054664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame5777' and @src = 'https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardExpiry&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController5771' and @title = 'Secure expiration date input frame']</value>
      <webElementGuid>97947c6e-a3cc-4b1a-91a4-b30e265c6aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
