<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Last Name___privateStripeFrame4376</name>
   <tag></tag>
   <elementGuidId>4a03c797-f301-4b72-b668-b433fa2bbb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame4376']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame4376&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a10df480-1538-4f9b-854e-fcac5fe32b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame4376</value>
      <webElementGuid>cefe6282-90ae-4c34-8a35-caed3cf061fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d461527e-a863-433b-89b2-1bfe7e9cc150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22c70096-b080-4076-846b-a69b2c8d54c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e72179a0-0c48-49c9-bad7-403e7d13e0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7d875e0a-5bca-48bc-8944-73ebf5609446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>5cf79117-ec7f-40ca-9409-8bfa25e50be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController4371</value>
      <webElementGuid>3fcb9b93-6ffd-49f8-aa12-9c8d8ed3d93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card number input frame</value>
      <webElementGuid>5386b144-385f-402e-b5e4-6e9724155781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_number-653b618d7b205&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>5372130b-69b8-45a1-acd5-33f9777494e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame4376']</value>
      <webElementGuid>d3f3cecf-40c1-4601-ad61-b312a0cba4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-page-card_number-653b618d7b205']/div/iframe</value>
      <webElementGuid>3aed7fd9-5902-4df6-bab6-8d77e059921a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e0d6f506-a5d7-4642-8b32-4268d0826711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame4376' and @src = 'https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController4371' and @title = 'Secure card number input frame']</value>
      <webElementGuid>f830b13a-70f5-4ee7-903d-a42dcd7206d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
