<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration Date___privateStripeFrame5778</name>
   <tag></tag>
   <elementGuidId>5340078b-3676-4d0a-be98-da521de52b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame5778']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame5778&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2a3d4d00-7345-4568-977d-43fe34b7ceb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame5778</value>
      <webElementGuid>7ae9a165-35a9-4f47-a714-a2c1d7003748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d188c5b-76d5-4558-a47c-da3206dd5d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f45c4b59-d011-44d4-b1d1-b073c5a7b93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2550b1f7-9f05-4617-95f6-a6b4d399e095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5349929e-43f8-4358-b64f-5a6c9ce000b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>c3c49506-6c1e-4a22-a7e6-eb61bb1650cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController5771</value>
      <webElementGuid>7bf5f87c-a255-4b5e-8ac1-37943e002452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure CVC input frame</value>
      <webElementGuid>d8d5bb5a-de0b-4366-8cc0-c2f04b536387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_cvc-653b618d7b205&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>6ab857bc-fe9b-403c-b641-88a800084ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame5778']</value>
      <webElementGuid>c5501bd3-68d3-442e-b959-635bc4f85cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-page-card_cvc-653b618d7b205']/div/iframe</value>
      <webElementGuid>6248e4a2-603f-4fca-aa93-a2fd6209bf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/iframe</value>
      <webElementGuid>d4fa35ff-6bb7-4005-b0a7-052385b3b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame5778' and @src = 'https://js.stripe.com/v3/elements-inner-card-3699308d7fe943c3d893d1c2e7a26e02.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=rgb(50%2C+50%2C+93)&amp;style[base][fontSize]=13px&amp;style[base][::placeholder][color]=rgb(50%2C+50%2C+93)&amp;style[base][::placeholder][fontSize]=13px&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_51HV93LABqnxcBWBVnfwKN4l5cJkbqfIT43oFzT1iqeuGe22Hdlb1shPKeWPEjatGqUXC3isHKLRisv4pneLHjOYe005LZuSAv3&amp;referrer=https%3A%2F%2Fpayment.page%2Ftemplates%2Fagency%2F&amp;controllerId=__privateStripeController5771' and @title = 'Secure CVC input frame']</value>
      <webElementGuid>d6ff3819-fecc-4a6d-93f7-c2cd6b048d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
