<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YOUR INFORMATION_email_address (1)</name>
   <tag></tag>
   <elementGuidId>569a2526-a780-4574-9303-8510c074dae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-page-email_address-653b618d7b205']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-page-email_address-653b618d7b205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>257749ab-e427-45ad-8da1-25a8e4ad4f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-page-email_address-653b618d7b205</value>
      <webElementGuid>447a415f-0d04-48bc-8b9b-2ce8165eb476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2ab4165-18dd-41c9-ba0b-929cb540e74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_address</value>
      <webElementGuid>b8336bbb-d3ef-4a12-b937-f4f825053e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>804042cd-faf0-413a-9e4e-ae379750206d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-email_address-653b618d7b205&quot;)</value>
      <webElementGuid>746cc37f-b1b8-471b-be1e-09ab8a028c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-page-email_address-653b618d7b205']</value>
      <webElementGuid>d5d43e2e-bf04-466c-975e-887abb8d4d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-form-653b618d7b205']/form/div[5]/div/div/input</value>
      <webElementGuid>c4ba58cc-9c92-41c9-9630-388caabf3f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>b4a1abbc-da15-4754-a6c6-f1516f6b258a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-page-email_address-653b618d7b205' and @type = 'text' and @name = 'email_address' and @placeholder = 'Email Address']</value>
      <webElementGuid>79a2ea10-f634-4fd0-8950-96f9196fb4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
