<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CVC_card_zip_code (3)</name>
   <tag></tag>
   <elementGuidId>90bb3a6f-a553-49c4-a2a3-e6bfdbf5beb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-page-card_zip_code-653b618d7b205']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-page-card_zip_code-653b618d7b205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ef707de-98a8-4fcf-b258-6ebe213adca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-page-card_zip_code-653b618d7b205</value>
      <webElementGuid>04f907cc-8bb2-4b26-b5db-faf3c496302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>802b9cbb-688d-44e6-a058-95e80c608ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_zip_code</value>
      <webElementGuid>ba40cc68-d4ed-4570-902b-fb415c2ecc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-card_zip_code-653b618d7b205&quot;)</value>
      <webElementGuid>1f993dba-fd4d-44f1-844f-4d9fea4c7889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-page-card_zip_code-653b618d7b205']</value>
      <webElementGuid>36684cfa-592d-407c-94c5-f9b490e0915e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-form-653b618d7b205']/form/div[5]/div/div[7]/input</value>
      <webElementGuid>971fb4f6-83cc-4b4c-bd4e-eae4ceea056c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>b60885e2-1050-4c4c-bc72-a129442e9567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-page-card_zip_code-653b618d7b205' and @type = 'text' and @name = 'card_zip_code']</value>
      <webElementGuid>b862ae95-4b2e-48c4-b3dd-956b12134535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
