<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cardnumber (2)</name>
   <tag></tag>
   <elementGuidId>50c4be21-f972-4df9-8faf-6429d336751c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cardnumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cardnumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>397000d0-2ec5-42e1-9c46-119b1e2b7179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputElement Input</value>
      <webElementGuid>a143ca27-ae39-4331-9104-65d180160dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>a3190b7d-0f29-4abf-ad96-fba9f333f0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d42656f-f0df-412f-9cdf-5e3a7dfab083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4790617d-6826-4663-bae1-5cb79a871744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>144502f2-0f35-4388-ac4f-e108ffd8f7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardnumber</value>
      <webElementGuid>775a44c5-5fa3-435a-b86d-5005b7943a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elements-stable-field-name</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>3efe4312-c156-45b2-b504-9ff404dfc627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4da78969-87f2-4f1d-b627-f5ed23b7a812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Credit or debit card number</value>
      <webElementGuid>475c41b9-b37d-4c78-bff3-da78ca818d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 1234 1234 1234</value>
      <webElementGuid>6526b6a3-f506-4cef-9a68-4893dbcc225e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a154f95-5c57-419a-a241-6ed85981c3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07b121a0-ddd6-44c3-8b49-3e04f1347f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>966d3ca2-4951-4c57-92a6-853424cda41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[@class=&quot;ElementsApp is-focused&quot;]/span[2]/div[@class=&quot;SplitCardField is-link-hidden previous-link-hidden&quot;]/div[@class=&quot;CardNumberField CardNumberField--ltr&quot;]/div[@class=&quot;CardNumberField-input-wrapper&quot;]/span[@class=&quot;InputContainer&quot;]/input[@class=&quot;InputElement Input&quot;]</value>
      <webElementGuid>e4476fc7-13bf-4bd5-85d1-d12b64ee0c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Agency  Payment Page/iframe_Last Name___privateStripeFrame8816</value>
      <webElementGuid>6455ffa1-42d7-4cdf-99b5-feecbb6adcf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cardnumber']</value>
      <webElementGuid>a7aad778-5366-4ebf-af44-79f5946c444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/span[2]/div/div/div[2]/span/input</value>
      <webElementGuid>6480440f-73e9-472f-8ca7-be0f56d20d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>a759ef32-2fc7-4a13-ac61-9721f2282661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardnumber' and @placeholder = '1234 1234 1234 1234']</value>
      <webElementGuid>44d7e565-902b-450f-82a0-e452291c5105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
