<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_last_name</name>
   <tag></tag>
   <elementGuidId>2b400528-9193-4a69-a15b-298dcf2530c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-page-last_name-653b618d7b205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e09d1600-bb8a-4ffa-8967-3a6407122678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-page-last_name-653b618d7b205</value>
      <webElementGuid>1f15d6c4-5219-4731-8c38-9beaed46acad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31c7c1ca-642d-4fc1-96d6-78a3c728d8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>b96532fe-418b-42cd-9b1b-841acafb1fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>17f851aa-9f81-4f2a-8daa-03b6697610f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-last_name-653b618d7b205&quot;)</value>
      <webElementGuid>f7accf07-4964-473a-bb5b-0129fadc9c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      <webElementGuid>d49f15ef-327f-409c-92c7-eb8d1d9699b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-form-653b618d7b205']/form/div[5]/div/div[3]/input</value>
      <webElementGuid>12f6cb4a-da05-44ef-9379-c421818dd048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c3f2b5cf-9fbc-4a9d-8909-60af9f341141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-page-last_name-653b618d7b205' and @type = 'text' and @name = 'last_name' and @placeholder = 'Last Name']</value>
      <webElementGuid>2486364a-ea05-4189-9b1c-d7a8facf629b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
