<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_last_name (1)</name>
   <tag></tag>
   <elementGuidId>eafca016-8b58-4f00-977a-2d724d34adc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-page-last_name-653b618d7b205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b764cf8-e959-48fc-b037-77fbc9ff48bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-page-last_name-653b618d7b205</value>
      <webElementGuid>f53df4cc-658d-49a1-b806-80620d820b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d93168c-13ed-4d92-9622-041da8f5724a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>90add9d9-c881-4ad8-9f29-ea1e48993396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>8d72be8b-f0e1-489c-a528-b544ca859243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-last_name-653b618d7b205&quot;)</value>
      <webElementGuid>b63aeb5a-080c-4f8f-bbe9-c74455d164cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      <webElementGuid>fdaa25a1-d33d-4644-a956-83558f1c3a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-form-653b618d7b205']/form/div[5]/div/div[3]/input</value>
      <webElementGuid>f29071e7-6d30-46a4-8ff6-e6809cfb129a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>fef43b96-d1d7-4fa0-a039-dcab08136105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-page-last_name-653b618d7b205' and @type = 'text' and @name = 'last_name' and @placeholder = 'Last Name']</value>
      <webElementGuid>f85a5584-a28c-44c5-a9cd-69809244a31d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
