<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_last_name (3)</name>
   <tag></tag>
   <elementGuidId>83375f16-8f04-4a9e-bf10-3f47fcccfa72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-page-last_name-653b618d7b205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83dbcba7-eca4-434e-a97d-7d43f7a9b376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-page-last_name-653b618d7b205</value>
      <webElementGuid>e929d12d-5dc1-4cb2-b241-dd850ae92817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92f27edd-7314-44a0-ade8-d8ac4be52569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>6ad6522e-bfc3-439a-a1fb-112cd6e46ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>b44f0d97-6002-46aa-80b1-3c91d670d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-page-last_name-653b618d7b205&quot;)</value>
      <webElementGuid>31f89452-8007-4628-b278-3edd2aa9c479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-page-last_name-653b618d7b205']</value>
      <webElementGuid>394428f7-5218-4eb8-a6d5-843292e5009b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-form-653b618d7b205']/form/div[5]/div/div[3]/input</value>
      <webElementGuid>1f41faa3-1917-45b9-9608-ef783f93756e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>cc31aa36-461f-4b8c-a6a7-5de039da6d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-page-last_name-653b618d7b205' and @type = 'text' and @name = 'last_name' and @placeholder = 'Last Name']</value>
      <webElementGuid>f0d16b2e-6491-429f-b633-7d6b67c6880d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
