<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_exp-date (1)</name>
   <tag></tag>
   <elementGuidId>2823b92b-0114-4145-becd-c06a0b1c24f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='exp-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;exp-date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa3d8ff9-9124-484f-be29-bda23026c2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputElement Input</value>
      <webElementGuid>00fb6cb4-9d07-450f-951b-7f91f16f07ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>10d1ff0b-2074-4e81-a717-8d2a064efd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f8ceed6-74dc-4b25-9f0b-e07769c94554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e57432e8-1cf4-41ba-ab41-4365f717c4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5394d45b-f95f-4a10-be93-443f1006f45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp-date</value>
      <webElementGuid>b985e51e-4ce6-4287-9ba5-abad222f615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elements-stable-field-name</name>
      <type>Main</type>
      <value>cardExpiry</value>
      <webElementGuid>d0387da7-6d3f-4269-a5f5-ce31b573938d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>3ee04c89-28d1-47e9-a3fa-84ce12e94fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Credit or debit card expiration date</value>
      <webElementGuid>fae389ba-1067-469c-9d83-e91e2ea58ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>5584fd6a-da0e-4d21-b326-546342b12b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f1f474a-e4e1-4d5b-88ef-bb9df3ec739d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a4e7fe0f-c2a6-42e3-8f8f-29b70e14e386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>07ab2a56-d035-49cd-a1a2-4c5f73eb5db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[@class=&quot;ElementsApp is-focused&quot;]/span[2]/div[@class=&quot;SplitCardField is-link-hidden previous-link-hidden&quot;]/span[@class=&quot;InputContainer&quot;]/input[@class=&quot;InputElement Input&quot;]</value>
      <webElementGuid>454c4b92-4167-4a33-8e48-e2dffa7dfb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Agency  Payment Page/iframe_Card Number___privateStripeFrame5777</value>
      <webElementGuid>97e76168-d04b-49ec-a80e-e1c07a6c5d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='exp-date']</value>
      <webElementGuid>4a3063e0-a973-48ba-80a2-1f788a5d5c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/span[2]/div/span/input</value>
      <webElementGuid>76b9670a-283b-44cd-9e7e-4fe168028175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>e9db0a5b-cf2c-489c-a662-ed65530b10e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'exp-date' and @placeholder = 'MM / YY']</value>
      <webElementGuid>6c9d7c04-29a5-4f0f-bfd2-ad8e6458b4aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
