<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_exp-date (2)</name>
   <tag></tag>
   <elementGuidId>5e69baef-5716-4187-b9b5-bd87da03a383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='exp-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;exp-date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acce1a36-2e71-4cea-a5e0-20114deb18d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputElement Input</value>
      <webElementGuid>1302c086-f82c-44e0-a0bb-123c3e622b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>e5f47dc8-8943-4bbc-9a43-6f5377c8ac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3d924f5-af6a-43a2-995c-99ac000eb87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7adef4b9-6582-4369-ae35-ee82c626d937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e48676c6-f585-4bac-8578-d093c7b78f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp-date</value>
      <webElementGuid>98e31c95-8ec1-4760-a9b9-6091b248cd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elements-stable-field-name</name>
      <type>Main</type>
      <value>cardExpiry</value>
      <webElementGuid>fbdff7ee-e805-4758-ac1d-e53a9ef40ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>dee4e51b-d62b-4343-8fac-1964cde5865b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Credit or debit card expiration date</value>
      <webElementGuid>9b4a008d-6ddd-4652-9ee7-ebcd02f3a3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>017774c5-3cf9-4f8a-a42e-aa6282df9f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>772bce46-13f3-4487-9001-7ab0ca71193f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>481f5762-a8f4-4d0c-add9-37849bd8d4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a21af215-8e1f-44ff-8bca-4ad3e547ef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[@class=&quot;ElementsApp is-focused&quot;]/span[2]/div[@class=&quot;SplitCardField is-link-hidden previous-link-hidden&quot;]/span[@class=&quot;InputContainer&quot;]/input[@class=&quot;InputElement Input&quot;]</value>
      <webElementGuid>b1490218-65d9-4ecd-a66c-63d3dcd623fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Agency  Payment Page/iframe_Your card number is invalid___privat_9e05e5</value>
      <webElementGuid>9dcd645c-96d5-42d6-bc1e-b9d6c3e8db5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='exp-date']</value>
      <webElementGuid>a2fe4d8a-e819-45db-b051-5faa4c910ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/span[2]/div/span/input</value>
      <webElementGuid>3b91157b-7705-48c1-bc2c-17410a4bc10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>5f1a6919-e026-4c70-a51e-2651fa61942d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'exp-date' and @placeholder = 'MM / YY']</value>
      <webElementGuid>88bb7118-0a20-4c1d-9fc8-f3f81589e032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
